spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:mysql://localhost:3306/auth_service}
    username: ${AUTH_DB_USERNAME:ecom}
    password: ${AUTH_DB_PASSWORD:ecom}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
