server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:mysql://localhost:3306/user_service}
    username: ${USER_DB_USERNAME:ecom}
    password: ${USER_DB_PASSWORD:ecom}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
